- name: Deploy playbook
  hosts: all
  become: yes

  tasks:
    - name: Create/Update a container
      docker_container:
        name: lbx-telebot
        image: '{{img}}'
        env_file: /home/sta/envs/telebot.env
        recreate: yes
        pull: true